# Use an official Node.js image
FROM node:20-alpine

# Set the environment to production
ENV NODE_ENV=production

# Set the working directory
WORKDIR /app

# Copy only the package.json and package-lock.json for installing dependencies
COPY package*.json ./

# Install production dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Run the server script directly for production
CMD ["node", "-r", "dotenv/config", "server.js"]