name: Deploy the Server to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'p2p-core-signaling/**'
      

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: zombie-file
          
      - name: Create .env File
        run: |
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/zombie-file/zombie-file/zombie-file-p2p-server:${{ github.sha }} ./p2p-core-signaling

      - name: Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/zombie-file/zombie-file/zombie-file-p2p-server:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy zombie-file-p2p-server \
            --image us-central1-docker.pkg.dev/zombie-file/zombie-file/zombie-file-p2p-server:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
